apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kvwpj3v1w-nodejs 
  janus-idp.io/tekton: kvwpj3v1w-nodejs
  backstage.io/kubernetes-id: kvwpj3v1w-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kvwpj3v1w-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  